#!/usr/bin/env python3
"""Drive the Hive Math Lab through a ladder of Project Euler problems, headlessly.

For each problem: state it in the ``solvers`` desk, pump the approvals queue
(``shell`` parks on every policy tier, so an unattended run has to answer it),
wait for the hive episode to end (a ``hive-report`` bubble on the desk), and
compare the integer the room converged on against the published answer.

Stdlib only, so it runs wherever ``python3`` does. Talks to a running
``opencompany serve`` (default ``http://127.0.0.1:8080``) whose auth mode is
``none``, or signs in as the manifest admin through the dev-code flow when the
host echoes one (loopback, no public URL).

    python3 scripts/hive-euler.py --problems 1,5,12,31,60,100
    python3 scripts/hive-euler.py --base http://127.0.0.1:8080 --desk solvers --timeout 1500

Exit status is the number of problems the room got wrong or failed to finish,
so a CI-style caller can treat zero as green. A JSON transcript of every run is
written next to the summary (``--out``) for reading afterwards.
"""

from __future__ import annotations

import argparse
import html
import http.cookiejar
import json
import os
import re
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from html.parser import HTMLParser
from pathlib import Path

SCOPE = "/api/v1/company"
ADMIN_EMAIL = "harness-e2e@tinyhumans.ai"
HIVE_REPORT_AUTHOR = "hive-report"
# Where a checkout of lucky-bai/projecteuler-solutions usually sits; the first
# that exists is the default for `--answers`, so a grade is available for every
# problem the fetcher can pull rather than only the hard-coded table.
DEFAULT_ANSWER_FILES = (
    "../projecteuler-solutions/Solutions.md",
    "../../projecteuler-solutions/Solutions.md",
    __import__("os").path.expanduser("~/work/projecteuler-solutions/Solutions.md"),
)

# `https://projecteuler.net/minimal=<N>` returns the problem's own HTML
# fragment with no title, no chrome, and no rate-limit worth working around
# for a script that runs one lab, not a scraper. Cached forever once fetched
# — a problem statement never changes.
FETCH_URL = "https://projecteuler.net/minimal={n}"
DEFAULT_CACHE_DIR = Path(os.path.expanduser("~/.cache/opencompany/euler"))

# Mirrors the block tags `minimal=<N>` actually emits (`<p>`, and Euler's own
# `<div class="note">` asides); a boundary here becomes a paragraph break.
_BLOCK_TAGS = {"p", "div", "li", "br"}
# `!<kind> [#topic] [>target] [^cite ...]`, matching the grammar
# `tinyhivemind-hive::trace::parse_line` reads a marker line under
# (`vendor/tinyhivemind/crates/tinyhivemind-hive/src/trace/mod.rs`) plus the
# `!pin` / `!unpin` markers `tinyhivemind::pins` reads separately. Only the
# marker line is ever journaled (`docs/spec/runtime/hivemind.md`), so a turn's
# `text` is already just this line.
MOVE_KINDS = (
    "propose",
    "support",
    "object",
    "evidence",
    "question",
    "defer",
    "commit",
    "pin",
)
_MARKER_RE = re.compile(
    r"^!(propose|support|object|refute|evidence|question|defer|commit|pin|unpin)\b"
)
_TOPIC_RE = re.compile(r"(?:^|\s)#(\S+)")
_MENTION_RE = re.compile(r"@([A-Za-z0-9_.-]+)")
_CITE_RE = re.compile(r"\^(\d+)")

# The ladder. Statements are given in full because the lab holds no `web`
# grant; answers are the published ones (projecteuler-solutions).
PROBLEMS: dict[str, dict[str, str]] = {
    "1": {
        "title": "Multiples of 3 or 5",
        "answer": "233168",
        "statement": (
            "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get "
            "3, 5, 6 and 9. The sum of these multiples is 23.\n\n"
            "Find the sum of all the multiples of 3 or 5 below 1000."
        ),
    },
    "5": {
        "title": "Smallest multiple",
        "answer": "232792560",
        "statement": (
            "2520 is the smallest number that can be divided by each of the numbers from 1 to "
            "10 without any remainder.\n\n"
            "What is the smallest positive number that is evenly divisible by all of the "
            "numbers from 1 to 20?"
        ),
    },
    "12": {
        "title": "Highly divisible triangular number",
        "answer": "76576500",
        "statement": (
            "The sequence of triangle numbers is generated by adding the natural numbers. So "
            "the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten "
            "terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...\n\n"
            "Let us list the factors of the first seven triangle numbers:\n"
            "  1: 1\n  3: 1,3\n  6: 1,2,3,6\n  10: 1,2,5,10\n  15: 1,3,5,15\n"
            "  21: 1,3,7,21\n  28: 1,2,4,7,14,28\n\n"
            "We can see that 28 is the first triangle number to have over five divisors.\n\n"
            "What is the value of the first triangle number to have over five hundred divisors?"
        ),
    },
    "14": {
        "title": "Longest Collatz sequence",
        "answer": "837799",
        "statement": (
            "The following iterative sequence is defined for the set of positive integers: "
            "n -> n/2 (n is even), n -> 3n + 1 (n is odd).\n\n"
            "Using the rule above and starting with 13, we generate the following sequence: "
            "13 -> 40 -> 20 -> 10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1. It can be seen that this "
            "sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has "
            "not been proved yet (Collatz Problem), it is thought that all starting numbers "
            "finish at 1.\n\n"
            "Which starting number, under one million, produces the longest chain?\n\n"
            "NOTE: Once the chain starts the terms are allowed to go above one million."
        ),
    },
    "31": {
        "title": "Coin sums",
        "answer": "73682",
        "statement": (
            "In the United Kingdom the currency is made up of pound (£) and pence (p). There "
            "are eight coins in general circulation: 1p, 2p, 5p, 10p, 20p, 50p, £1 (100p), and "
            "£2 (200p).\n\n"
            "It is possible to make £2 in the following way: 1×£1 + 1×50p + 2×20p + 1×5p + "
            "1×2p + 3×1p.\n\n"
            "How many different ways can £2 be made using any number of coins?"
        ),
    },
    "60": {
        "title": "Prime pair sets",
        "answer": "26033",
        "statement": (
            "The primes 3, 7, 109, and 673, are quite remarkable. By taking any two primes "
            "and concatenating them in any order the result will always be prime. For "
            "example, taking 7 and 109, both 7109 and 1097 are prime. The sum of these four "
            "primes, 792, represents the lowest sum for a set of four primes with this "
            "property.\n\n"
            "Find the lowest sum for a set of five primes for which any two primes "
            "concatenate to produce another prime."
        ),
    },
    "92": {
        "title": "Square digit chains",
        "answer": "8581146",
        "statement": (
            "A number chain is created by continuously adding the square of the digits in a "
            "number to form a new number until it has been seen before.\n\n"
            "For example, 44 -> 32 -> 13 -> 10 -> 1 -> 1 and 85 -> 89 -> 145 -> 42 -> 20 -> "
            "4 -> 16 -> 37 -> 58 -> 89. Therefore any chain that arrives at 1 or 89 will "
            "become stuck in an endless loop. What is most amazing is that EVERY starting "
            "number will eventually arrive at 1 or 89.\n\n"
            "How many starting numbers below ten million will arrive at 89?"
        ),
    },
    "100": {
        "title": "Arranged probability",
        "answer": "756872327473",
        "statement": (
            "If a box contains twenty-one coloured discs, composed of fifteen blue discs and "
            "six red discs, and two discs were taken at random, it can be seen that the "
            "probability of taking two blue discs, P(BB) = (15/21) x (14/20) = 1/2.\n\n"
            "The next such arrangement, for which there is exactly a 50% chance of taking two "
            "blue discs at random, is a box containing eighty-five blue discs and thirty-five "
            "red discs.\n\n"
            "By finding the first arrangement to contain over 10^12 = 1,000,000,000,000 discs "
            "in total, determine the number of blue discs that the box would contain."
        ),
    },
    "145": {
        "title": "How many reversible numbers are there below one-billion?",
        "answer": "608720",
        "statement": (
            "Some positive integers n have the property that the sum [ n + reverse(n) ] "
            "consists entirely of odd (decimal) digits. For instance, 36 + 63 = 99 and "
            "409 + 904 = 1313. We will call such numbers reversible; so 36, 63, 409, and 904 "
            "are reversible. Leading zeroes are not allowed in either n or reverse(n).\n\n"
            "There are 120 reversible numbers below one-thousand.\n\n"
            "How many reversible numbers are there below one-billion (10^9)?"
        ),
    },
}


class _StatementExtractor(HTMLParser):
    """Strip `minimal=<N>`'s HTML down to text, keeping paragraph breaks.

    `$...$` LaTeX is never touched — it is not a tag, so it simply passes
    through `handle_data` unchanged, dollar signs and all.
    """

    BREAK = "\x00"

    def __init__(self) -> None:
        super().__init__(convert_charrefs=False)
        self.parts: list[str] = []

    def handle_starttag(self, tag: str, attrs) -> None:  # noqa: ANN001
        if tag in _BLOCK_TAGS:
            self.parts.append(self.BREAK)

    def handle_endtag(self, tag: str) -> None:
        if tag in _BLOCK_TAGS:
            self.parts.append(self.BREAK)

    def handle_data(self, data: str) -> None:
        self.parts.append(data)

    def handle_entityref(self, name: str) -> None:
        self.parts.append(html.unescape(f"&{name};"))

    def handle_charref(self, name: str) -> None:
        self.parts.append(html.unescape(f"&#{name};"))


def clean_statement_html(raw: str) -> str:
    """Tags out, entities unescaped, `$...$` kept as-is, blank runs collapsed."""
    extractor = _StatementExtractor()
    extractor.feed(raw)
    paragraphs = []
    for chunk in "".join(extractor.parts).split(_StatementExtractor.BREAK):
        collapsed = re.sub(r"\s+", " ", chunk).strip()
        if collapsed:
            paragraphs.append(collapsed)
    return "\n\n".join(paragraphs)


def fetch_statement(pid: str, cache_dir: Path, do_fetch: bool, log) -> str | None:
    """The problem statement for `pid`, from the cache or the network.

    A hit under `cache_dir` is trusted forever — a published statement does
    not change — so a second run of the same ladder makes zero requests.
    """
    cache_file = cache_dir / f"{pid}.txt"
    if cache_file.exists():
        return cache_file.read_text(encoding="utf-8")
    if not do_fetch:
        return None
    url = FETCH_URL.format(n=pid)
    req = urllib.request.Request(url, headers={"User-Agent": "hive-euler/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:  # noqa: S310
            raw = resp.read().decode("utf-8", errors="replace")
    except (urllib.error.URLError, OSError, TimeoutError) as err:
        log(f"!! fetch failed for problem {pid}: {err}")
        return None
    text = clean_statement_html(raw)
    if not text:
        return None
    cache_dir.mkdir(parents=True, exist_ok=True)
    cache_file.write_text(text, encoding="utf-8")
    return text


_ANSWER_LINE = re.compile(r"^\s*(\d+)\.\s+(\S+)\s*$")


def load_answers(path: str | None) -> dict[str, str]:
    """Published answers from a `Solutions.md`-shaped file: `123. 456789` lines."""
    if not path:
        return {}
    answers: dict[str, str] = {}
    try:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                m = _ANSWER_LINE.match(line)
                if m:
                    answers[m.group(1)] = m.group(2)
    except OSError as err:
        raise SystemExit(f"--answers {path}: {err}") from None
    return answers


def resolve_problem(
    pid: str, answers: dict[str, str], cache_dir: Path, do_fetch: bool, log
) -> dict[str, str] | None:
    """A problem's title/statement/answer, offline table first, fetch to fill gaps."""
    known = PROBLEMS.get(pid)
    statement = (known or {}).get("statement")
    if do_fetch or statement is None:
        fetched = fetch_statement(pid, cache_dir, do_fetch, log)
        if fetched:
            statement = fetched
    if statement is None:
        log(f"!! no statement for problem {pid} (not fetched, not in the offline table)")
        return None
    answer = answers.get(pid) or (known or {}).get("answer")
    if answer is None:
        log(f"!! no published answer known for problem {pid}; will not be able to grade it")
    title = (known or {}).get("title", f"Problem {pid}")
    return {"title": title, "statement": statement, "answer": answer}


def parse_problem_spec(spec: str) -> list[str]:
    """`"200-210,233,301"` -> ordered, de-duplicated problem ids."""
    seen: set[str] = set()
    ids: list[str] = []
    for chunk in spec.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        if "-" in chunk:
            lo_s, _, hi_s = chunk.partition("-")
            lo, hi = int(lo_s), int(hi_s)
            if hi < lo:
                lo, hi = hi, lo
            span = (str(n) for n in range(lo, hi + 1))
        else:
            span = (chunk,)
        for pid in span:
            if pid not in seen:
                seen.add(pid)
                ids.append(pid)
    return ids


def analyze_transcript(turns: list[dict], report_text: str | None) -> dict:
    """Count moves, speakers, mentions and citations; check who backed the winner.

    `carried_supporters_other_than_proposer` is the direct check on the
    failure a live run showed: a room can converge on a proposal with two
    `!propose`s and nobody's `!support` behind either. `None` when the report
    named no topic (deadlocked/exhausted/idle) or nobody ever proposed it.
    """
    moves = {kind: 0 for kind in MOVE_KINDS}
    speakers: set[str] = set()
    mentions = 0
    citations = 0
    proposer_of: dict[str, str] = {}
    supporters_of: dict[str, set[str]] = {}

    for turn in turns:
        text = (turn.get("text") or "").strip()
        author = turn.get("author")
        if author:
            speakers.add(author)
        if not text:
            continue
        mentions += len(_MENTION_RE.findall(text))
        citations += len(set(_CITE_RE.findall(text)))
        first_line = text.splitlines()[0]
        match = _MARKER_RE.match(first_line)
        if not match:
            continue
        kind = match.group(1)
        bucket = "pin" if kind == "unpin" else kind
        if bucket in moves:
            moves[bucket] += 1
        topic_match = _TOPIC_RE.search(first_line)
        topic = topic_match.group(1) if topic_match else None
        if not (topic and author):
            continue
        if kind == "propose":
            proposer_of.setdefault(topic, author)
        elif kind in ("support", "commit"):
            supporters_of.setdefault(topic, set()).add(author)

    carried_topic = None
    if report_text:
        m = re.search(r"#(\S+)", report_text)
        if m:
            carried_topic = m.group(1).rstrip(".,;:")

    diverse_support = None
    if carried_topic is not None:
        proposer = proposer_of.get(carried_topic)
        backers = supporters_of.get(carried_topic, set())
        diverse_support = any(a != proposer for a in backers)

    return {
        "moves": moves,
        "distinct_speakers": len(speakers),
        "mentions": mentions,
        "citations": citations,
        "carried_topic": carried_topic,
        "carried_supporters_other_than_proposer": diverse_support,
    }


class Host:
    """A cookie-carrying HTTP client for one OpenCompany host."""

    def __init__(self, base: str) -> None:
        self.base = base.rstrip("/")
        self.jar = http.cookiejar.CookieJar()
        self.opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(self.jar))

    def call(self, method: str, path: str, body: dict | None = None, timeout: float = 120):
        data = None if body is None else json.dumps(body).encode()
        req = urllib.request.Request(self.base + path, data=data, method=method)
        req.add_header("accept", "application/json")
        if data is not None:
            req.add_header("content-type", "application/json")
        try:
            with self.opener.open(req, timeout=timeout) as resp:
                raw = resp.read()
                return resp.status, (json.loads(raw) if raw else None)
        except urllib.error.HTTPError as err:
            raw = err.read()
            try:
                return err.code, json.loads(raw)
            except ValueError:
                return err.code, raw.decode(errors="replace")

    def sign_in(self) -> None:
        """No-op when auth is `none`; otherwise the loopback dev-code flow."""
        status, _ = self.call("GET", f"{SCOPE}/chat/history?limit=1")
        if status == 200:
            return
        status, body = self.call("POST", f"{SCOPE}/auth/request", {"email": ADMIN_EMAIL})
        code = (body or {}).get("dev_code") if isinstance(body, dict) else None
        if not code:
            raise SystemExit(f"sign-in: no dev_code from auth/request ({status}: {body})")
        status, body = self.call("POST", f"{SCOPE}/auth/verify", {"code": code})
        if status >= 300:
            raise SystemExit(f"sign-in: verify refused ({status}: {body})")

    # -- the operator's two jobs: stating the problem and answering approvals --

    def say(self, desk: str, text: str, timeout: float = 3600) -> None:
        """State one problem in `desk`, holding the POST open for the episode.

        `timeout` has to be the caller's own per-problem budget rather than a
        constant. The cycle runs the whole episode synchronously inside this
        one request, so a socket timeout below the budget kills the room's
        turns mid-flight and the run reports `timeout` for an episode whose
        own budget was never spent — which is exactly what a `--timeout 5400`
        run did against the hard-coded 3600 that used to be here.
        """
        status, body = self.call(
            "POST", f"{SCOPE}/chat", {"text": text, "chat": desk}, timeout=timeout
        )
        if status >= 300:
            raise RuntimeError(f"chat POST failed ({status}): {body}")

    def approve_all(self) -> list[str]:
        status, body = self.call("GET", f"{SCOPE}/approvals")
        if status != 200 or not isinstance(body, list):
            return []
        approved = []
        for approval in body:
            aid = approval.get("id")
            status, _ = self.call(
                "POST", f"{SCOPE}/approvals/{aid}", {"verdict": "approve", "detach": True}
            )
            if status < 300:
                approved.append(approval.get("kind", "?"))
        return approved

    def history(self, desk: str, limit: int = 200) -> list[dict]:
        query = urllib.parse.urlencode({"desk": desk, "limit": limit})
        status, body = self.call("GET", f"{SCOPE}/chat/history?{query}")
        if status != 200 or not isinstance(body, list):
            return []
        return body


INT = re.compile(r"\d{1,3}(?:,\d{3})+|\d+")


def integers_in(text: str) -> list[str]:
    return [t.replace(",", "") for t in INT.findall(text)]


def wait_for_report(
    host: Host, desk: str, after_id: int, timeout: float, log, failure=None
) -> tuple[dict | None, list[dict]]:
    """Poll the desk until a hive-report bubble newer than `after_id` lands."""
    deadline = time.time() + timeout
    seen: set[str] = set()
    approved_total: list[str] = []
    while time.time() < deadline:
        if failure:
            log(f"    !! chat POST failed: {failure[0]}")
            return None, [m for m in host.history(desk) if int(m.get("id", "0")) > after_id]
        approved = host.approve_all()
        if approved:
            approved_total.extend(approved)
            log(f"    approved: {', '.join(approved)}")
        messages = [m for m in host.history(desk) if int(m.get("id", "0")) > after_id]
        for m in messages:
            if m["id"] not in seen:
                seen.add(m["id"])
                first = m.get("text", "").strip().splitlines()[:1]
                log(f"    [{m['id']}] {m.get('author')}: {first[0] if first else ''}")
        # The close is the last `hive-report` row that is not a failed-turn
        # notice ("@theorist's turn did not finish: …"); those share the author
        # because they are host-authored, but the room continues after them.
        report = next(
            (
                m for m in reversed(messages)
                if m.get("author") == HIVE_REPORT_AUTHOR
                and not m.get("text", "").lstrip().startswith("@")
            ),
            None,
        )
        if report:
            return report, messages
        time.sleep(5)
    return None, [m for m in host.history(desk) if int(m.get("id", "0")) > after_id]


def run_problem(host: Host, desk: str, pid: str, problem: dict, timeout: float, log) -> dict:
    before = host.history(desk, limit=1)
    after_id = int(before[-1]["id"]) if before else 0
    text = (
        f"Project Euler {pid}: {problem['title']}.\n\n{problem['statement']}\n\n"
        "Decide the answer as a desk: propose a candidate only once a program has printed it, "
        "support only a number you independently checked, and object to anything that did not "
        "come out of a run."
    )
    log(f"== Problem {pid} ({problem['title']}) — expecting {problem['answer'] or 'unknown'}")
    started = time.time()
    # The chat POST holds open for the whole episode (the cycle runs it
    # synchronously), and `shell` parks for approval inside it — so the
    # operator's two jobs have to run concurrently: state the problem on a
    # thread, and pump approvals from here while it runs.
    failure: list[BaseException] = []

    def state() -> None:
        try:
            # A little past the reader's own deadline, so the POST outlives the
            # wait rather than racing it: whichever fires first should be the
            # deadline that was asked for, and that is `wait_for_report`'s.
            host.say(desk, text, timeout=timeout + 60)
        except BaseException as err:  # noqa: BLE001 — surfaced below
            failure.append(err)

    poster = threading.Thread(target=state, daemon=True)
    poster.start()
    report, messages = wait_for_report(host, desk, after_id, timeout, log, failure)
    # `wait_for_report` can return on its own timeout while the POST above is
    # still open — `poster` is a daemon thread and is never otherwise joined,
    # so without this the next problem's POST could start while this one is
    # still in flight, and both would touch the same desk state concurrently.
    # Bounded, not indefinite: a `shell` call still parked for approval could
    # keep the POST open well past our own deadline.
    poster.join(timeout=60)
    if poster.is_alive():
        log("    !! poster thread still running after report/timeout — its POST may still "
            "be in flight; the next problem may overlap this episode")
    elapsed = round(time.time() - started, 1)
    turns = [m for m in messages if m.get("author") not in (HIVE_REPORT_AUTHOR,) and not m.get("mine")]
    activity = analyze_transcript(turns, report.get("text") if report else None)
    outcome = {
        "problem": pid,
        "title": problem["title"],
        "expected": problem["answer"],
        "elapsed_s": elapsed,
        "turns": len(turns),
        "report": report.get("text") if report else None,
        "messages": messages,
        **activity,
    }
    answer = problem["answer"]
    if report is None:
        outcome["verdict"] = "timeout"
    else:
        rtext = report.get("text", "")
        # `ending_summary()` (src/hivemind/types.rs) says "The desk settled on
        # #topic after N turns" for a converged room; the other endings say
        # "deadlocked", "spent its N-turn budget", or the room never opened.
        # "converged" itself never appears in any of those templates, so the
        # only string worth matching on is "settled on".
        converged = "settled on" in rtext
        found = integers_in(rtext)
        # The report names the carried topic; a topic is usually the number
        # itself (`#233168`) but a room may name it otherwise, so fall back to
        # the last supporting line's integers. Restricted to turns whose own
        # marker line names the *carried* topic: without that, a room that
        # churned onto a different `#topic` partway through can be graded
        # "correct" because some unrelated turn happens to mention the right
        # integer for a different reason entirely.
        carried_topic = activity.get("carried_topic")
        if answer and answer not in found and carried_topic is not None:
            for m in reversed(turns):
                text = (m.get("text") or "").strip()
                if not text:
                    continue
                topic_match = _TOPIC_RE.search(text.splitlines()[0])
                topic = topic_match.group(1).rstrip(".,;:") if topic_match else None
                if topic != carried_topic:
                    continue
                if answer in integers_in(text):
                    found.append(answer)
                    break
        outcome["converged"] = converged
        if answer is None:
            outcome["verdict"] = "converged (no known answer)" if converged else "undecided"
        else:
            outcome["verdict"] = (
                "correct" if converged and answer in found else
                "wrong" if converged else
                "undecided"
            )
    log(f"   -> {outcome['verdict']} after {len(turns)} turns in {elapsed}s")
    return outcome


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base", default="http://127.0.0.1:8080")
    ap.add_argument("--desk", default="solvers")
    ap.add_argument(
        "--problems",
        default="1,5,12,31,60,100",
        help="comma-separated ids and ranges, e.g. '200-210,233,301'",
    )
    ap.add_argument("--timeout", type=float, default=1500, help="seconds per problem")
    ap.add_argument("--out", default="hive-euler-results.json")
    ap.add_argument(
        "--fetch",
        dest="fetch",
        action="store_true",
        default=True,
        help="pull statements from projecteuler.net/minimal=<N> when not cached (default on)",
    )
    ap.add_argument(
        "--no-fetch",
        dest="fetch",
        action="store_false",
        help="offline: only the hard-coded PROBLEMS table and the local cache",
    )
    ap.add_argument(
        "--cache-dir",
        default=str(DEFAULT_CACHE_DIR),
        help="where fetched statements are cached (default ~/.cache/opencompany/euler)",
    )
    ap.add_argument(
        "--answers",
        default=next(
            (c for c in DEFAULT_ANSWER_FILES if __import__("os").path.exists(c)), None
        ),
        help="a Solutions.md-shaped file of '<n>. <answer>' lines to grade against",
    )
    ap.add_argument(
        "--stop-after-failures",
        type=int,
        default=0,
        help="stop the ladder after this many non-correct verdicts in a row (0 = never)",
    )
    args = ap.parse_args()

    def log(line: str) -> None:
        print(line, flush=True)

    answers = load_answers(args.answers)
    cache_dir = Path(args.cache_dir)
    host = Host(args.base)
    host.sign_in()
    results = []
    consecutive_failures = 0
    for pid in parse_problem_spec(args.problems):
        problem = resolve_problem(pid, answers, cache_dir, args.fetch, log)
        if problem is None:
            continue
        outcome = run_problem(host, args.desk, pid, problem, args.timeout, log)
        results.append(outcome)
        with open(args.out, "w") as fh:
            json.dump(results, fh, indent=2)
        # A room that converged on a problem this driver cannot grade is not a
        # failure of the room; only a wrong, undecided or timed-out episode
        # counts toward the stop.
        if outcome["verdict"] in ("correct", "converged (no known answer)"):
            consecutive_failures = 0
        else:
            consecutive_failures += 1
            if args.stop_after_failures and consecutive_failures >= args.stop_after_failures:
                log(
                    f"!! stopping after {consecutive_failures} non-correct verdicts in a row "
                    f"(--stop-after-failures {args.stop_after_failures})"
                )
                break

    log("")
    header = (
        "problem | verdict                  | turns | seconds | speakers | "
        + " | ".join(m[:4] for m in MOVE_KINDS)
        + " | @men | ^cit | diverse"
    )
    log(header)
    log("-" * len(header))
    for r in results:
        moves = r.get("moves", {})
        move_cols = " | ".join(f"{moves.get(k, 0):>4}" for k in MOVE_KINDS)
        diverse = r.get("carried_supporters_other_than_proposer")
        diverse_s = "yes" if diverse is True else "no" if diverse is False else "-"
        log(
            f"{r['problem']:>7} | {r['verdict']:<24} | {r['turns']:>5} | {r['elapsed_s']:>7} | "
            f"{r.get('distinct_speakers', 0):>8} | {move_cols} | {r.get('mentions', 0):>4} | "
            f"{r.get('citations', 0):>4} | {diverse_s:>7}"
        )
    # A room that converged with no known answer to grade against is a
    # success by `--stop-after-failures`'s own predicate (it resets
    # `consecutive_failures` to 0 for exactly this verdict) — the exit code
    # must agree, or a ladder run against an incomplete answers file exits
    # non-zero even though every room actually converged.
    return sum(
        1 for r in results if r["verdict"] not in ("correct", "converged (no known answer)")
    )


if __name__ == "__main__":
    sys.exit(main())
